### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by chetan-yg** [varun-naharia/VNImageScanner#3]
I dragged and drop the VNCameraScanner.swift to my project, But I am getting few errors. Anything I am missing out?

![screen shot 2017-09-18 at 11 43 25 am](https://user-images.githubusercontent.com/16645590/30530715-c431d03e-9c66-11e7-950e-4193f0391318.png)
![screen shot 2017-09-18 at 11 43 47 am](https://user-images.githubusercontent.com/16645590/30530717-c448b4ac-9c66-11e7-9e9b-9e55a9a45094.png)
![screen shot 2017-09-18 at 11 44 06 am](https://user-images.githubusercontent.com/16645590/30530716-c4360c26-9c66-11e7-969f-384334bbbad6.png)

**Comment by varun-naharia** [comment]
please let me know your xcode version

**Comment by chetan-yg** [comment]
XCode Version 8.3.3.
Swift 3

**Comment by varun-naharia** [comment]
have you tried to run demo project is there also the same error ? I have build and tested the in xcode 8.3.3 and swift 3 with no error

**Comment by chetan-yg** [comment]
The demo project is working fine. But In my project, it is not working. Are there any settings I am missing?

**Comment by varun-naharia** [comment]
Please create a demo and send link to me so I can check what is missing
