### ISSUE TITLE
Camera Is not opening and scanning 

### ISSUE THREAD

**Issue by gauravvirkhare** [varun-naharia/VNImageScanner#4]
I am using your library but my demo project is not opening camera and detecting edges.
i just made view as VNImagescnner view and used the its methods.
I am stuck from 2 days.
So please help me.

[DemoVNimagescanner.zip](https://github.com/varun-naharia/VNImageScanner/files/1570712/DemoVNimagescanner.zip)

**Comment by varun-naharia** [comment]
Please check your zip file it doesn't contain code to check.

**Comment by gauravvirkhare** [comment]
Please check demo 

[Democamerascanner.zip](https://github.com/varun-naharia/VNImageScanner/files/1570775/Democamerascanner.zip)

**Comment by varun-naharia** [comment]
Please wait I'll respond to when I found exact reason because of this is happening

**Comment by varun-naharia** [comment]
From where you did download the code ?

**Comment by gauravvirkhare** [comment]
From Github 
Did i followed the correct integration procedure?
Please check and let know\, because i m sensing issue is might be with integration.

**Comment by varun-naharia** [comment]
I think  you didn't download code from https://github.com/varun-naharia/VNImageScanner but from https://github.com/iCoder333/VNImageScanner, am I right ?

At this time I am not sure why your code is not working but it looks like you download code from different location.

**Comment by varun-naharia** [comment]
Yes I checked you did't used files from my repo.
